#!/bin/bash
for f in lib/* ; do . $f ; done;

#-----------------------------------------------
# Контейнер
#-----------------------------------------------
imagename=u16            # Псевдоним начального образа
container=dc1            # Имя контейнера
zpoolname=t1             # Имя zpool
tmpfile=tmp              # Имя временного файла для работы скрипта
#-----------------------------------------------
# Сеть
#-----------------------------------------------
subnet=192.168.64.0
address=192.168.64.3
gateway=192.168.64.1
netmask=255.255.255.0
nameservers=8.8.8.8
dnssearch=hd.onway.ws

#-----------------------------------------------
# bind9
#-----------------------------------------------
dhcprange="192.168.64.25 192.168.64.255"
zone=hd.onway.ws                      # прямая зона
arpa=64.168.192                       # обратная зона
fzone=/var/lib/bind/db.onway.ws       # файл прямой зоны
farpa=/var/lib/bind/db.onway.ws.rev   # файл обратной зоны
nsname=ns1                            # nameserver
nsaddr=$address                       # nameserver полный ip адрес
dcname=$container                     # имя контроллера домена
dcarpa=3                              # адрес в зоне arpa [3].64.168.192
rtname=router                         # имя шлюза
rtaddr=$gateway                       # полный ip адрес шлюза
rtarpa=1                              # адрес в зоне arpa [1].64.168.192

#-----------------------------------------------
# samba ad dc
#-----------------------------------------------
realm=WD.HD.ONWAY.WS
domain=WD
hostname=DC1
adminpass=Qwert12

#-----------------------------------------------
# MAIN
#-----------------------------------------------

lxd_container_create
lxd_container_set_acl
network_conf
install_samba4_bind9_dhcp
samba_ad_dc
samba_ad_dc_conf
bind9_named_conf_options
bind9_named_conf_local
bind9_zone
bind9_zone_rev
apparmor_usr_sbin_named
dhcp_conf
apparmor_usr_sbin_dhcpd
nameservers=127.0.0.1
network_conf


