#!/bin/bash
# install bind9 dhcp samba4 ad dc
# установка samba4 как контроллера домена актив директории в контейнере lxd

for f in lib/* ; do . $f ; done;

#-----------------------------------------------
# Контейнер
#-----------------------------------------------
imagename=u16            # Псевдоним начального образа
container=dc1            # Имя контейнера
zpoolname=t1             # Имя zpool
tmpfile=tmp              # Имя временного файла для работы скрипта
#-----------------------------------------------
# Сеть
#-----------------------------------------------
subnet=192.168.64.0
address=192.168.64.3
gateway=192.168.64.1
netmask=255.255.255.0
nameservers=8.8.8.8
dnssearch=hd.onway.ws

#-----------------------------------------------
# bind9
#-----------------------------------------------
dhcprange="192.168.64.25 192.168.64.255"
zone=hd.onway.ws                      # прямая зона
arpa=64.168.192                       # обратная зона
fzone=/var/lib/bind/db.onway.ws       # файл прямой зоны
farpa=/var/lib/bind/db.onway.ws.rev   # файл обратной зоны
nsname=ns1                            # nameserver
nsaddr=$address                       # nameserver полный ip адрес
dcname=$container                     # имя контроллера домена
dcarpa=3                              # адрес в зоне arpa [3].64.168.192
rtname=router                         # имя шлюза
rtaddr=$gateway                       # полный ip адрес шлюза
rtarpa=1                              # адрес в зоне arpa [1].64.168.192

#-----------------------------------------------
# samba ad dc
#-----------------------------------------------
realm=WD.HD.ONWAY.WS
domain=WD
hostname=DC1
adminpass=Qwert12

#-----------------------------------------------
# MAIN
#-----------------------------------------------

lxd_container_create        # Установка нового контейнера
lxd_container_set_acl       # Включить поддержку ACL файловой системы контейнера
network_conf                # Конфигурация фиксированного IP адреса
install_samba4_bind9_dhcp   # Установка пакетов
samba_ad_dc                 # Инициализация домена
samba_ad_dc_conf            # Конфигурация [global] smb.conf
bind9_named_conf_options    # Конфигурация named.conf.options
bind9_named_conf_local      # Конфигурация named.conf.local
bind9_zone                  # Конфигурация прямой зоны
bind9_zone_rev              # Конфигурация обратной зоны
apparmor_usr_sbin_named     #
dhcp_conf                   # Конфигурация dhcp.conf
apparmor_usr_sbin_dhcpd     #
nameservers=127.0.0.1       # Замена адреса на свой nameservers
network_conf                # Конфигурация сети но новый nameservers
