#!/bin/bash
for f in lib/* ; do . $f ; done;

#-----------------------------------------------
# Контейнер
#-----------------------------------------------
imagename=u16            # Псевдоним начального образа
container=smb            # Имя контейнера
zpoolname=t1             # Имя zpool
tmpfile=tmp              # Имя временного файла для работы скрипта

#-----------------------------------------------
# Сеть
#-----------------------------------------------
subnet=192.168.64.0
address=192.168.64.4
gateway=192.168.64.1
netmask=255.255.255.0
nameservers=192.168.64.3
dnssearch=wd.hd.onway.ws

#-----------------------------------------------
# samba
#-----------------------------------------------
realm=WD.HD.ONWAY.WS
workgroup=WD
domain=$dnssearch
adminpass=Qwert12

lxd_container_create
lxd_container_set_acl
network_conf
samba_mem_hosts
install_samba4_member
samba_mem_krb5_conf
samba_mem_conf
samba_mem_nsswitch_conf
samba_mem_pam
samba_mem_join
