#!/bin/bash

#-----------------------------------------------
# Контейнер
#-----------------------------------------------
imagename=u16            # Псевдоним начального образа
container=smb            # Имя контейнера
zpoolname=t1             # Имя zpool
tmpfile=tmp              # Имя временного файла для работы скрипта

#-----------------------------------------------
# Сеть
#-----------------------------------------------
subnet=192.168.64.0
address=192.168.64.4
gateway=192.168.64.1
netmask=255.255.255.0
nameservers=192.168.64.3
dnssearch=wd.hd.onway.ws

#-----------------------------------------------
# samba
#-----------------------------------------------
realm=WD.HD.ONWAY.WS
workgroup=WD
domain=$dnssearch
adminpass=Qwert12

lxd_container_create
lxd_container_set_acl
