#!/bin/bash
host_system_net_brige() {

cat<<EOF >/mnt/etc/network/interfaces.d/$3
auto br0 
iface br0 inet static
        address $n_address
        netmask $n_netmask
        network $n_network
        broadcast $n_broadcast
        gateway $n_gateway
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers $n_nameservers
        dns-search $n_search
        # bridge options
        bridge_ports $n_bridge_ports
iface $n_bridge_ports inet manual
EOF
}
