#!/bin/bash
host_system_net_brige() {

if [[ yes = $static ]]; then        
	
apt install -y bridge-utils
	
cat<<EOF >/mnt/etc/network/interfaces.d/$NI
auto br0 
iface br0 inet static
        address $n_address
        netmask $n_netmask
        network $n_network
        broadcast $n_broadcast
        gateway $n_gateway
        # dns-* options are implemented by the resolvconf package, if installed
        dns-nameservers $n_nameservers
        dns-search $n_search
        # bridge options
        bridge_ports $n_bridge_ports

iface $n_bridge_ports inet manual
EOF
	
else

cat<<EOF >/mnt/etc/network/interfaces.d/$NI
auto br0
iface br0 inet dhcp
    	bridge_ports $n_bridge_ports
	
iface $n_bridge_ports inet manual
EOF

fi
}
