#!/bin/bash

host_LXD() {

echo "install LXD"

apt install -y lxd

echo "Name of the storage backend to use (dir or zfs): zfs"
echo "Create a new ZFS pool (yes/no)? no"
echo "Name of the existing ZFS pool or dataset: $PN"
echo "Would you like LXD to be available over the network (yes/no)? no"
echo "Do you want to configure the LXD bridge (yes/no)? yes"
#Warning: Stopping lxd.service, but it can still be activated by:
#  lxd.socket
#LXD has been successfully configured.

}
