#!/bin/bash
host_grub_install() {
if [[ $TD = BIOS ]]; then

apt install -y grub-pc

elif [[ $TD = UEFI ]]; then

#DS1=/dev/disk/by-id/ata-WDC_WD30EZRX-22D8PB0_WD-WCC4N1LURJNZ
 
apt install -y dosfstools
mkdosfs -F 32 -n EFI $DS1-part2
mkdir /boot/efi
echo PARTUUID=$(blkid -s PARTUUID -o value $DS1) /boot/efi vfat defaults 0 1 >> /etc/fstab
mount /boot/efi
apt install -y grub-efi-amd64

else
echo TD not defined
exit 1
fi

echo -----------------------------------------------------------------------------------------
echo zfs
grub-probe /
echo -----------------------------------------------------------------------------------------
echo "update-initramfs: Generating /boot/initrd.img-4.4.0-21-generic"
update-initramfs -c -k all
}
