#!/bin/bash
host_basic_system_environment() {
locale -a
dpkg-reconfigure locales
dpkg-reconfigure console-setup
dpkg-reconfigure keyboard-configuration
dpkg-reconfigure tzdata
 
cat<<EOF >/etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu xenial main universe
deb-src http://archive.ubuntu.com/ubuntu xenial main universe
 
deb http://security.ubuntu.com/ubuntu xenial-security main universe
deb-src http://security.ubuntu.com/ubuntu xenial-security main universe
 
deb http://archive.ubuntu.com/ubuntu xenial-updates main universe
deb-src http://archive.ubuntu.com/ubuntu xenial-updates main universe
EOF
 
ln -s /proc/self/mounts /etc/mtab
apt update
apt install -y mc nano ssh
apt install -y ubuntu-minimal
apt install -y --no-install-recommends linux-image-generic
apt install -y zfs-initramfs
 
useradd -m $USERNAME -c "sudo user" -s /bin/bash  # new username 
echo -e "$PASS\n$PASS\n" | passwd $USERNAME # password username 
usermod -aG sudo $USERNAME # add username in sudo group
}
