#!/bin/bash
#-----------------------------------------------
# samba_mem_krb5_conf
#-----------------------------------------------

samba_mem_krb5_conf () {
cat <<EOF >./$tmpfile
[libdefaults]
 default_realm = $realm
 ticket_lifetime = 24000
 default_tgs_entypes = rc4-hmac des-cbc-md5
 default_tkt__enctypes = rc4-hmac des-cbc-md5
 permitted_enctypes = rc4-hmac des-cbc-md5
 dns_lookup_realm = true
 dns_lookup_kdc = true
 dns_fallback = yes

[realms]
 $realm = {
  kdc = $domain:88
  default_domain = $domain
 }

[domain_realm]
# So are leading fullstops
 .$domain = $realm
 $domain = $realm

[appdefaults]
 pam = {
   debug = false
   ticket_lifetime = 36000
   renew_lifetime = 36000
   forwardable = true
   krb4_convert = false
 }

[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log
EOF

lxc file push --mode=644 ./$tmpfile $container/etc/krb5.conf
rm ./$tmpfile
}

